### ISSUE TITLE
🐛 Fix: Required Minimum Balance is ~2 algo higher than minimum balance requirements reported by MyAlgo

### ISSUE THREAD

**Issue by ericsharma** [algodex/algodex-sdk#200]
# ℹ Overview
Our calculation for minimum balance:
```
function getMinAmount(
    wallet,
) {
  console.debug('in getMinWalletBalance. Checking: ' + wallet.address);
  console.debug({wallet});

  let minAmount = 0;

  if (wallet['created-apps']) {
    minAmount += 100000 * (wallet['created-apps'].length); // Apps
  }
  if (wallet['assets']) {
    minAmount += wallet['assets'].length * 100000;
  }
  if (
    !isUndefined(wallet['apps-total-schema']) &&
    wallet['apps-total-schema']['num-uint']
  ) {
    // Total Ints
    minAmount += (25000+3500) * wallet['apps-total-schema']['num-uint'];
  }
  if (
    !isUndefined(wallet['apps-total-schema']) &&
    wallet['apps-total-schema']['num-byte-slice']
  ) {
    const numByteSlice = wallet['apps-total-schema']['num-byte-slice'];
    minAmount += (25000+25000) * numByteSlice; // Total Bytes
  }
  minAmount += 1000000;

  return minAmount;
}
```
In conjunction with `getWalletAlgoBalance()` is resulting in unexpected behavior for users of the SDK. They are getting insufficient balance error messages. 
If the extra minimum balance is a requirement for our service, we should add it to the documentation, if not, we should change the way we calculate minimum balance.

**Comment by atrefonas** [comment]
It's possible Algorand added a new sdk function that calculates the minimum balance. Could be a good thing to check for first.

**Comment by ericsharma** [comment]
@atrefonas So as far as I can tell there isn't any standard function for calculating the minimum balance. Certain endpoints provide the minimum balance of an account while others do not. For instance `https://algoindexer.algoexplorerapi.io/v2/accounts/{address}` (Indexer developed by Algorand Inc.) does not provide the minimum balance while `https://indexer.algoexplorerapi.io/v2/accounts/{address}` (Indexer developed by Rand Labs) does provide the minimum balance.

**Comment by atrefonas** [comment]
Let me check with Randlabs and see if they will tell us the formula.

**Comment by ericsharma** [comment]
@atrefonas It should be resolved now. Check put the open PR if you want to see what the issue was. 
https://github.com/algodex/algodex-sdk/pull/203

**Comment by atrefonas** [comment]
Good find
