### ISSUE TITLE
Fix: PureStake commit to main needs to be reverted

### ISSUE THREAD

**Issue by ericsharma** [algodex/algodex-sdk#306]
# ℹ Overview

[This Commit](https://github.com/algodex/algodex-sdk/commit/49c89db7d2de99a15066ddfa0f084bb9663e6a24) needs to be reverted because the addition of the `x-api-key` throws errors when not using pure-stake. 

## Example
If you cancel an order on the front end, [compileProgram.js](https://github.com/algodex/algodex-sdk/blob/49c89db7d2de99a15066ddfa0f084bb9663e6a24/lib/teal/compile/compileProgram.js#L23) throws the error:

```66711302:1 Access to XMLHttpRequest at 'https://node.testnet.algoexplorerapi.io/v2/teal/compile' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field x-api-key is not allowed by Access-Control-Allow-Headers in preflight response.```

### 📝 Related Issues

#282

**Comment by atrefonas** [comment]
Instead of reverting, can you instead fix it so if the URL includes algoexplorer then it will not add x-api-key? It is needed for Purestake.

**Comment by atrefonas** [comment]
Or even better, only add it if using Purestake.
